KEY_BYTE_SIZE = 32
IV_BYTE_SIZE = 16
PADDING_BLOCK_SIZE = 128
USB_DIR = "./USB/"
PRIVATE_PEM = USB_DIR + "private.pem"
PUBLIC_PEM = USB_DIR +"public.pem"
MAX_CHAIN_ENCRYPTION = 3
CHORD_PRIV_PEM = "./private.pem"
CHORD_PUB_PEM = "./public.pem"
TEMP_PRIV_PEM = "./tempPriv.pem"
TEMP_PUB_PEM = "./tempPub.pem"
SERVER_IP = "ec2-18-191-99-22.us-east-2.compute.amazonaws.com"
SERVER_PORT = 23245
